version: "3.5"
services:
  pgsql:
    container_name: xport_pgsql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xport
    expose:
      - 5432
    image: postgres:latest
    networks:
      internal:
        ipv4_address: 192.168.7.2

  redis:
    container_name: xport_redis
    networks:
      internal:
        ipv4_address: 192.168.7.3
    image: redis:latest
    expose:
      - 6379

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.7.0/24
